[2025-07-04T02:51:52.508+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_ingest_dag.fetch_and_insert manual__2025-07-04T02:51:45.894365+00:00 [queued]>
[2025-07-04T02:51:52.531+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_ingest_dag.fetch_and_insert manual__2025-07-04T02:51:45.894365+00:00 [queued]>
[2025-07-04T02:51:52.532+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-07-04T02:51:52.559+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): fetch_and_insert> on 2025-07-04 02:51:45.894365+00:00
[2025-07-04T02:51:52.582+0000] {standard_task_runner.py:57} INFO - Started process 212 to run task
[2025-07-04T02:51:52.586+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_ingest_dag', 'fetch_and_insert', 'manual__2025-07-04T02:51:45.894365+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/weather_ingest_dag.py', '--cfg-path', '/tmp/tmpkau8qang']
[2025-07-04T02:51:52.591+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask fetch_and_insert
[2025-07-04T02:51:53.092+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_ingest_dag.fetch_and_insert manual__2025-07-04T02:51:45.894365+00:00 [running]> on host b87c05c3cf38
[2025-07-04T02:51:53.573+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='harsha' AIRFLOW_CTX_DAG_ID='weather_ingest_dag' AIRFLOW_CTX_TASK_ID='fetch_and_insert' AIRFLOW_CTX_EXECUTION_DATE='2025-07-04T02:51:45.894365+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-04T02:51:45.894365+00:00'
[2025-07-04T02:51:53.600+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-04T02:51:53.626+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/airflow/dags/fetch_weather.py']
[2025-07-04T02:51:53.719+0000] {subprocess.py:86} INFO - Output:
[2025-07-04T02:51:54.159+0000] {subprocess.py:93} INFO - python: can't open file '/opt/airflow/dags/fetch_weather.py': [Errno 2] No such file or directory
[2025-07-04T02:51:54.170+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-07-04T02:51:54.205+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-07-04T02:51:54.261+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_ingest_dag, task_id=fetch_and_insert, execution_date=20250704T025145, start_date=20250704T025152, end_date=20250704T025154
[2025-07-04T02:51:54.474+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task fetch_and_insert (Bash command failed. The command returned a non-zero exit code 2.; 212)
[2025-07-04T02:51:54.766+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-04T02:51:54.849+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
